# Data Structure / Data Type
## Data type is a data classification, like container

In [1]:
# Int - 5
# Floats - 2.5

In [2]:
x = 7

In [3]:
y = 7

In [4]:
z = y

# NOT making a copy, edits to z will change the dataset

In [5]:
id(x)

4334840304

In [6]:
id(y)

4334840304

In [7]:
id(z)

4334840304

In [8]:
## 7 is a value stored in python memory
## x and y are pointers that point to the same object
## Python built-in functions
### x, y, z pointing and sharing the same object
## Garbage collector

## String

In [9]:
word = "apple"

## String is a sequence of charactors, single or double quotes
## No limit to length of the string

In [10]:
## The functions to use for data types

# type()
# dir()
# help()

In [11]:
type(word)

str

In [12]:
word = 7

In [13]:
type(word)

int

In [14]:
word = 'apple'

In [15]:
## dir function saves time
## dir tells you the list of attributes/methods available
### underscores, private methods
print(dir(word))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [16]:
word

'apple'

In [17]:
# Usually don't use these methods, much easier to use +
word.__add__("orange")

'appleorange'

In [18]:
word + "orange"

'appleorange'

In [19]:
## See other methods to be used right away, no underscore
help(word.upper)

Help on built-in function upper:

upper() method of builtins.str instance
    Return a copy of the string converted to uppercase.



In [20]:
# Returns a copy, string is IMMUTABLE, cannot be changed
# Mutability is a programming concept that is important
# Immutable objects tent to be faster
# Every method of a string will create a copy
word.upper()

'APPLE'

In [21]:
# word can be over-written by assigning word.upper() to word again

In [22]:
# Jupyter build-in perks
## Save data every 3 minuts
## use tab after ".", to let Jupyter give help, or "shift tab" to show details of the variable

In [23]:
# String is a collection of charactors, so can be indexed

In [24]:
word = word.upper()

In [25]:
word

'APPLE'

In [26]:
word[0]

'A'

In [27]:
word[-1]

'E'

In [28]:
# "-" is for direction
word[-5]

'A'

In [29]:
id(word[0])

4336321072

In [30]:
id(word)

4391748784

In [31]:
# String is immutable
# word[0] is a different copy

In [32]:
# To slice
##[start: stop: step] # stop is exclusive

SyntaxError: invalid syntax (1163204254.py, line 2)

In [33]:
word[1:3]

'PP'

In [34]:
word[3:5]

'LE'

In [35]:
word[3:]

'LE'

In [36]:
## Negative step reverse the whole string

## always 0 based, the last is always [-1]
word[::-1]

'ELPPA'

In [37]:
word[-1]

'E'

In [38]:
string = "aAbBcCdDeE"

In [39]:
# Get all the capitalized letter
string[1::2]

'ABCDE'

In [40]:
# lowercase letters, backwards
string[-2::-2]

'edcba'

In [41]:
address = "115 W 30th St., New York, NY, 12345"

In [42]:
zipcode = address[-5:]
zipcode

'12345'

In [43]:
address[len(address)-5:]

'12345'

In [44]:
len(address)-5

30

## List

In [45]:
alist = []

In [46]:
alist.append(7)
alist.append(5)
alist.append(3)

In [47]:
alist

[7, 5, 3]

In [48]:
alist.append("apple")

In [49]:
alist

[7, 5, 3, 'apple']

In [50]:
## list is mutable
## list is slow

In [51]:
alist

[7, 5, 3, 'apple']

In [52]:
alist.remove("apple")

In [53]:
alist

[7, 5, 3]

In [54]:
alist.sort()

In [55]:
# index the list, same way as string
alist[0]

3

In [56]:
alist[0] = 100

In [57]:
alist

[100, 5, 7]

In [58]:
# Suggest list to be homogeneous, not merge data types
# something might work, but not efficient
# want to move fast, and efficient

In [59]:
for banana in alist:
    print("banana = ", banana)

banana =  100
banana =  5
banana =  7


In [60]:
for banana in alist:
    print("banana = ", banana)
    break

banana =  100


In [61]:
## Python two types of loops
## 1. definite loop: for-loop, no. of times known
## 2. 

In [62]:
shopping_list = ["bananas", "oranges", "mangos"]
item = input("What else should i get? ")
print(item.split())
shopping_list.append(item)

for food in shopping_list:
    if food == "beer":
        print("Are you old enough to buy a beer")
    print("Do not forget to buy", food)

What else should i get? 
[]
Do not forget to buy bananas
Do not forget to buy oranges
Do not forget to buy mangos
Do not forget to buy 


## List comprehensions, faster solution
## Not using "append"

In [63]:
numbers = [1, 2, 3, 4, 5, 5, 5, 5]
fives = []
# [5, 5, 5, 5]

In [64]:
for number in numbers:
    if number == 5:
        fives.append(number)

In [65]:
fives

[5, 5, 5, 5]

In [66]:
# Ke 
[ i for i in numbers if i==5 ]

[5, 5, 5, 5]

In [67]:
## Append downloads append library
## Use list comprehension is fast, twice faster

In [68]:
# Capitalize first letter

weak = ['mon', 'tue', 'wed']
days = [i.capitalize() for i in weak]
days

['Mon', 'Tue', 'Wed']

In [69]:
# Capitalize first letter

weak = ['mon', 'tue', 'wed']
days = [i.upper() for i in weak]
days

['MON', 'TUE', 'WED']

In [70]:
[f"{day.upper()[0]}{day.lower()[1:]}" for day in weak]

['Mon', 'Tue', 'Wed']

In [71]:
def str_upper(s):
    return s.upper()

In [72]:
## Apply function to iterate terms
map(str_upper, weak)

In [73]:
## Map is a way to do "for loop", function map
## applies a function to all items in iterable
list(map(str_upper, weak))

['MON', 'TUE', 'WED']

## Use lambda

### lambda is anonymous function, no name function
### uses no memory
### do not need to use this function again

In [74]:
def add(a, b):
    return a + b

## Function is a block of reusable code
### lambda (variables) : (expression)
### never uses return, if always returns
### lambda cannot be used in its own, must be assigned to something 
### Or used as a helper function

In [75]:
f = lambda banana, orange: banana + orange

In [76]:
f(5,6)

11

In [77]:
week = ['mon', 'tue', 'wed']

In [78]:
list(map(lambda x: x.upper(), week))

['MON', 'TUE', 'WED']

In [79]:
## Create a function take a number from user and 
## print ("Even") if number is even or ("Odd") if number is odd

number_str = input("Enter a number: ")
number_int = int(number_str)
if number_int%2 == 0:
    print("Even")
else:
    print("Odd")

Enter a number: 


ValueError: invalid literal for int() with base 10: ''

In [80]:
def print_even_odd_number(x):
    if x%2 == 0:
        print("Even")
    else:
        print("Odd")

In [81]:
print_even_odd_number(5)

Odd


In [82]:
print_even_odd_number(4)

Even


In [83]:
### rewrite with lambda

list(map(lambda n : "Even" if int(n)%2 == 0 else "Odd", [1, 2, 3]))

['Odd', 'Even', 'Odd']

## Tuple
### What if we need to save multiple data types

In [84]:
alist = [1, 2, 3]

In [85]:
alist[0] = 100

In [86]:
# tuple
t = tuple(alist)

In [87]:
t

(100, 2, 3)

In [88]:
t[0] = 1

TypeError: 'tuple' object does not support item assignment

In [89]:
## Tuple does not support item assignemnt
### List is mutable
### Tuple is immutable, faster than list

In [90]:
## What if we store heterogenous items
## Employee database, ok for tuple to have different data types
employee = (345, "John", "Johnson", "IT")

In [91]:
type(employee)

tuple

In [92]:
employee[1]

'John'

In [93]:
## Assign at the same time (simultaneous)
em_id, first, last, dep = employee

In [94]:
## Gets result

divmod(5, 3) # use shift + tab

(1, 2)

In [95]:
a, b = divmod(5, 3)

In [96]:
a

1

In [97]:
## iterate through a tuple
for item in employee:
    print(item)

345
John
Johnson
IT


In [98]:
# don't confuse with slicing
range(10) 
# stop is exclusive
for i in range(10):
    print (i)

0
1
2
3
4
5
6
7
8
9


In [99]:
for i in range(1, 11, 1):
    print (i)

1
2
3
4
5
6
7
8
9
10


In [100]:
word = "apple"
len(word)
for i in range(10, 0, -1):
    print (i)

10
9
8
7
6
5
4
3
2
1


In [101]:
type(len(word))

int

In [102]:
word = "apple"

for i in range(len(word)):
    print(len(word)-i-1, word[len(word)-i-1])

4 e
3 l
2 p
1 p
0 a


In [103]:
# Palindrome problem
for i in range(len(word)-1, -1, -1):
    print(i, word[i])

4 e
3 l
2 p
1 p
0 a


## Set

In [104]:
## Collection of UNIQUE and IMMUTABLE items
s = set("APPLE")

In [105]:
s

{'A', 'E', 'L', 'P'}

In [106]:
s = set(['APPLE', 'APPLE', 'APPLE', 'BANANA'])

In [107]:
s

{'APPLE', 'BANANA'}

In [108]:
## Use case, find intersect between two collections
s = {1, 2, 3, 4}
s2 = {2, 4, 5, 6}
s.intersection(s2)

{2, 4}

In [109]:
s.difference(s2)

{1, 3}

## Dictionary

In [110]:
## Set and Dict both of curly brackets
## Collection of pairs of keys and values

In [111]:
d = {}
d["Mary"] = 43242344

In [112]:
d["John"] = 435435434

In [113]:
## One to one relationship, if not, multiple?
## 1. keys gotta be unique
## 2. Only immutable datatype could be used as a key in the dictionary
#### tuple? Yes. 
####  (eg. the employee data can be used as the key)
#### True or False can be used as keys in the dictionary
####  boolean can be used a s key

In [114]:
True == False

False

In [115]:
d[True] = None

In [116]:
d

{'Mary': 43242344, 'John': 435435434, True: None}

In [117]:
del d[True]

In [118]:
d

{'Mary': 43242344, 'John': 435435434}

In [119]:
## Items stored in dictionary or list, which one if faster?
### List: need to iterate through the list to find "bananas"
### Dictionary: if key is unique, one operation to find "bananas", it is a hash table


In [120]:
d.keys()

dict_keys(['Mary', 'John'])

In [121]:
## Dictionary: 
### fetch data from dictionary
### look over the keys

In [122]:
alist = list(d.keys())
alist.sort()
alist

['John', 'Mary']

In [123]:
menu = {"Hamburger": 5.75, "Nachos": 9.99, \
       "Salad": 3.99}

In [124]:
menu = {"Hamburger":5.75, "Nachos":9.99, "Salad":3.99}
sale = {}
## reduce prices by 10%

In [125]:
## Iterate through a dictionary

for item in menu:
    print(item, menu[item])

Hamburger 5.75
Nachos 9.99
Salad 3.99


In [126]:
# A list of tuples
menu.items()

dict_items([('Hamburger', 5.75), ('Nachos', 9.99), ('Salad', 3.99)])

In [127]:
for k, v in menu.items():
    print(k, v)

Hamburger 5.75
Nachos 9.99
Salad 3.99


In [128]:
sale = {}
for k, v in menu.items():
    v_new = float(v)*0.9
    sale[k] = v_new

In [129]:
sale

{'Hamburger': 5.175, 'Nachos': 8.991, 'Salad': 3.591}

In [130]:
## use dictionary comprehension
sale = {key:value*0.9 for (key,value) in menu.items()}
sale

{'Hamburger': 5.175, 'Nachos': 8.991, 'Salad': 3.591}

In [131]:
menu

{'Hamburger': 5.75, 'Nachos': 9.99, 'Salad': 3.99}

In [132]:
sale

{'Hamburger': 5.175, 'Nachos': 8.991, 'Salad': 3.591}

In [133]:
menu['Hamburger']

5.75

In [134]:
# If key is correct, return value
# If key not on the menu, get default value
# Keep code running
menu.get("Hamburger", "Nope")
menu.get("Cookie", "Nope")

'Nope'

## Try and Except
### Keep the program running

In [135]:
7 + "7"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [136]:
try:
    number = 7 + "7"
except:
    print("Check that number")
    number = 0

Check that number


In [137]:
menu["Salad"] = [3.99, 5.99, 9.99]

In [138]:
menu

{'Hamburger': 5.75, 'Nachos': 9.99, 'Salad': [3.99, 5.99, 9.99]}

In [139]:
menu.keys()

dict_keys(['Hamburger', 'Nachos', 'Salad'])

In [140]:
type(menu["Salad"])

list

In [141]:
menu["Salad"][-1]

9.99

In [142]:
menu["Salad"] = {'S': 3.99, "M": 5.99, "L": 9.99}

In [143]:
menu['Salad']['S']

3.99

In [144]:
len(menu)

3

## Args and kwargs

In [145]:
def add(a,b):
    total = a + b
    return total

In [146]:
## Function takes arguments, but we do not how many, come in "tuples"
def add(*args):
    print(type(args))

In [147]:
add(1, 2, 3)

<class 'tuple'>


In [148]:
# args come in tuples
def add(word, *args):
    print(word, sum(args))

In [149]:
add("Hello", 1,2,3)

Hello 6


In [150]:
def my_fun(word, *args, **kwargs):
    print(word)
    print(args)
    # keyword arguments
    print(kwargs)

In [151]:
my_fun(1, 2, 3, 4, 5, name='Jeter', team='Yankees', sport="baseballl")

1
(2, 3, 4, 5)
{'name': 'Jeter', 'team': 'Yankees', 'sport': 'baseballl'}


## For loop vs While loop

In [152]:
## For loop goes one by one in the sequence
#### don't do nested loops
## While loop faster as it checks conditions


In [153]:
# print

for i in range(1,11):
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 

In [154]:
## nested loops, how many operations
## increase runtime complexity, code run slower

for i in range(1,11):
    for j in range(1, 11):
        print("{:4}".format(i*j), end=" ")

   1    2    3    4    5    6    7    8    9   10    2    4    6    8   10   12   14   16   18   20    3    6    9   12   15   18   21   24   27   30    4    8   12   16   20   24   28   32   36   40    5   10   15   20   25   30   35   40   45   50    6   12   18   24   30   36   42   48   54   60    7   14   21   28   35   42   49   56   63   70    8   16   24   32   40   48   56   64   72   80    9   18   27   36   45   54   63   72   81   90   10   20   30   40   50   60   70   80   90  100 

In [155]:
## Note: will do vectorized operation

In [156]:
## while loop faster, depends on conditions
while condition:
    do something

SyntaxError: invalid syntax (550072352.py, line 3)

In [157]:
counter = 0 
# infinite loop
#while counter < 5:
#    print(counter)

while counter < 5:
    print(counter)
    counter += 1

0
1
2
3
4


In [158]:
flagVar = True

# be very careful with flagVar
while flagVar:
    print("hello")
    flagVar = False

hello


In [159]:
## Plotting libraries

shopping_list = ["bananas", "oranges", "mangos"]

item = input("What else should i get? ")
while item != "stop":
    if item not in set(shopping_list):
        shopping_list.append(item)
    item = input("What else should i get?")
print(shopping_list)

What else should i get? milk
What else should i get?stop
['bananas', 'oranges', 'mangos', 'milk']


In [160]:
## Shopping list case
# Can we use while and keep asking what else should I get? till user input stop 

## Numpy Arrays and Pandas

In [161]:
import numpy as np
import pandas as pd

In [162]:
alist = [10, 20, 30, 40, 50]

In [163]:
alist + 5 # does not work

TypeError: can only concatenate list (not "int") to list

In [164]:
alist + alist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [165]:
a = np.array(alist)

In [166]:
a

array([10, 20, 30, 40, 50])

In [167]:
# Why is numpy array faster than list?
## List is mutable, python does not store spaces for these items
## Python need time to collect items, allocate memory
## List is heterogeneous, python quietly runs type(), takes tool and slow
## For numpy array, all items stored in the same space, always homogeneous
## - No way to squeeze in another dataset
## - One dimensional vector, and perform vector operations

In [168]:
# type of container
print(type(a))

<class 'numpy.ndarray'>


In [169]:
## data type of objects in container
a.dtype

dtype('int64')

In [170]:
a

array([10, 20, 30, 40, 50])

In [171]:
a[0] = 100.99

In [172]:
## converts a[0] from float to int, due to the homogenous trait of numpy array
a

array([100,  20,  30,  40,  50])

In [173]:
## vectorized operations
## Never ever for loop for an array
a + 5

array([105,  25,  35,  45,  55])

In [174]:
## Use universal functions only (ufunctions)
## What are the ufunctions? Built into numpy

In [175]:
sum(a)

240

In [176]:
## np.sum is faster and more efficient

np.sum(a)

240

In [177]:
big_array = np.random.rand(1000000)

In [178]:
big_array

array([0.49903934, 0.60058696, 0.8444942 , ..., 0.79385062, 0.19395023,
       0.55699568])

In [179]:
%timeit sum(big_array)

39.2 ms ± 1.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [180]:
%timeit np.sum(big_array)

193 µs ± 637 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [181]:
## numpy array can be 2-D
blist = [[10,20,30],[40,50,60],[70,80,90]]

In [182]:
## np array has 6 major attributes
### b.ndim, b.dtype, b.shape, b.size, b.itemsize (bytes per item), b.nbytes
b = np.array(blist)

In [183]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [184]:
b.ndim

2

In [185]:
b.dtype

dtype('int64')

In [186]:
b.shape

(3, 3)

In [187]:
b.size

9

In [188]:
b.itemsize

8

In [189]:
b.nbytes

72

In [190]:
# [start:stop, start: stop], first for rows, second for columns, separated for comma

In [191]:
subset = b[0:2, 0:2]

In [192]:
subset[0,0] = 100

In [193]:
subset

array([[100,  20],
       [ 40,  50]])

In [194]:
## Original array (b), not only the subset is changed, zoom in changes the original
b

array([[100,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90]])

In [195]:
## remember to use .copy() otherwise still working on the original dataset

subset = b[1:3, 1:3].copy()
subset[0, 0] = 500

In [196]:
subset

array([[500,  60],
       [ 80,  90]])

In [197]:
b

array([[100,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90]])

### Broadcasting

In [198]:
## array operations
### addition, subtraction and etc
### linear algebra rules, already built into the data structure

In [199]:
one = np.array([1, 2, 3])
two = np.array([4, 5, 6])

In [200]:
# adds number to each item of the 1-D array
one + 5

array([6, 7, 8])

In [201]:
three = np.ones((3, 3))
three

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [202]:
three + one

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [203]:
np.zeros((3,3)) + 6

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [204]:
np.zeros((3,3)) + 6.0

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [205]:
b[0,0] = 10

In [206]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Pandas
### two major data structure
### 1. Series (1 dim) , 2. dataframes (2 dim)

In [207]:
pd.DataFrame

## Can be thought of as a dict-like container for Series objects

pandas.core.frame.DataFrame

In [208]:
df = pd.DataFrame(b)

In [ ]:
# Dataframe got 3 major attributes
## 1. columns, index and values
## Primary key, relational database
### eg. how to pick from database, always unique, index is from SQL
## usually use labels as column numbers

df

In [209]:
df = pd.DataFrame(b, columns = ["A", "B", "C"])

In [210]:
df["A"][0]

10

In [212]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [213]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [214]:
df.values

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [215]:
## Can we manipulate np.array more efficiently?
## Attach index and columns to numpy array
## Pandas is built on top of numpy
## Dataframe inherited all behavior of numpy array

In [216]:
df

A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

#### df slicing

In [217]:
df["B"]

0    20
1    50
2    80
Name: B, dtype: int64

In [218]:
type(df["B"])

pandas.core.series.Series

In [219]:
df

A   B   C
0  10  20  30
1  40  50  60
2  70  80  90